### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by danblaker** [chloerei/active_service#3]
https://github.com/chloerei/active_service/blob/bd1d9503aa4be76991a8093d003306793e3071e5/lib/rails/generators/service/service_generator.rb#L6

Great joke gem whether or not you fix this typo: "an service" should be "a service". And no way am I going through the trouble of forking and generating a pull request :-) Too busy building services...

**Comment by chloerei** [comment]
Fixed, Thanks : )
